### ISSUE TITLE
Missing pear and pecl commands

### ISSUE THREAD

**Issue by stuartshields** [Chassis/v8js#34]
When trying to install v8js on Altis, we have an issue with the `pear` and `pecl` commands working. A work around is to `vagrant provision` after the box has been built.

```
Error: /Stage[main]/V8js::Extension/Exec[install archive tar]: Could not evaluate: Could not find command 'pear'

Error: Could not find command 'pecl'
Error: /Stage[main]/V8js::Extension/Exec[pecl channel-update pecl.php.net]/returns: change from notrun to 0 failed: Could not find command 'pecl'
Notice: /Stage[main]/V8js::Extension/Exec[pecl install v8js]: Dependency Exec[pecl channel-update pecl.php.net] has failures: true
Warning: /Stage[main]/V8js::Extension/Exec[pecl install v8js]: Skipping because of failed dependencies
```

**Comment by kucrut** [comment]
I'm not sure it has something to do with v8js though, because in my case, the error was different.

Here's the output of `composer chassis init`: https://pastebin.com/k73f2n2U

And here's the output of `vagrant provision` after: https://pastebin.com/LCCuzgkN

**Comment by BronsonQuick** [comment]
@stuartshields If you add the rest of your output from the initial provision to the issue also the output of a `vagrant provision` after that I might be able to work out the dependency ordering from that seeing I don't have my laptop.

**Comment by roborourke** [comment]
Puppet is being a massive garbage fire essentially. I've been trying to fix this all day - part of the problem was that the `mcrypt` extension has conflicting definitions for installing `php-pear`.

The real problem comes when you define a different PHP version to the default one - the `php-pear` package seems to be removed along with the current PHP version but by that point puppet has already decided it's installed.

**Comment by roborourke** [comment]
Fixed in https://github.com/Chassis/Chassis/pull/722
